### ISSUE TITLE
Set timeout for GenServer.call (default is 5 seconds)

### ISSUE THREAD

**Issue by jeffdeville** [urbint/cortex#11]
I'm getting some timeouts due to some long-running feature tests, and tests of 3rd party systems that do not update immediately.  I'm assuming there was a reason that `call` was used instead of `cast`.  If that's the case, please look at the forthcoming PR that sets the timeouts to infinity.

**Comment by rschmukler** [comment]
My gut says that this ought to be configurable. The reason we do it as a call instead of a cast is because we want to create piplining. For example, we don't run tests if compilation fails.

@wpcarro and @russmatney are both out of town this week so I want to wait for their feedback before implementing a solution.

**Comment by jeffdeville** [comment]
Yeah, I don't disagree w/ you.  It feels like that ought to be the case to me as well.  But I did it this way for the following reasons:

1. I didn't want to add configuration and thus code bulk that wasn't needed. Figured I'd leave the decision to you.
2. Almost any default you come up with will have reasonable, and sometimes frequent (in the case of pry) reasons for needing to change it.  eg:  I think test runs that don't get the --trace flag default to 60 seconds. That said, because you're running this in IEX, you can pry, at which point 60 seconds would be annoying.  As for compilation, I have had issues with really long compilation times as well (https://elixirforum.com/t/how-to-determine-why-elixir-compilation-w-a-macro-is-taking-202seconds/6322).  
3. It felt like infinite timeouts would be bad, but I couldn't articulate any scenarios where having them would be a negative.

Thanks for taking a look, Ryan!

**Comment by wpcarro** [comment]
@jeffdeville thanks for the issue. I'm looking into this now. @russmatney and I agree with the points that you outlined above.

Any timeout amount feels arbitrary to us. Point 3 is probably the most interesting:

> It felt like infinite timeouts would be bad, but I couldn't articulate any scenarios where having them would be a negative.

We feel the same way. I'm opting to merge your PR and then offer configuration if later down the road `:infinity` timeouts are realized to be bad.

**Comment by wpcarro** [comment]
Merged #12
