### ISSUE TITLE
-m: inotifywait: command not found

### ISSUE THREAD

**Issue by Aleksion** [urbint/cortex#15]
Suddenly running Cortex has started throwing this error.
Meaning it doesn't detect file changes anymore.

Any idea what might cause this?

**Comment by glittershark** [comment]
This happened to me too - installing inotifywait (via `inotify-tools` on Linux for me) fixed the problem

**Comment by Aleksion** [comment]
But isn't inotifywait a linux tool? There are similar tools for mac, but they'll go by another name and fail. I'll try it out though.

**Comment by Aleksion** [comment]
Clearing my build folder did the trick. `rm -rf _build`
That was apparently causing a cascade of small issues. 
Still receiving the inotifywait error, but i don't think that's caused by cortex. Feel free to close this

**Comment by russmatney** [comment]
Glad you found a fix, and thanks for documenting it here!

**Comment by glittershark** [comment]
this may be different after #13
