### ISSUE TITLE
roadmap credo

### ISSUE THREAD

**Issue by rvcas** [urbint/cortex#2]
I found this on [r/elixir](https://www.reddit.com/r/elixir/) and decided to poke around the code base cause this seems like a nice addition to the workflow.

I started putting some stuff together to integrate credo but I have a few questions before I do a bunch of stuff.

##### Questions:
1. Are any of the maintainers working on this in some local branch?
1. How do people (at least the maintainers) envision this working with credo?
1. Do we provide the default configs for credo and then allow users to override them with their on `.credo.exs`?
1. With the addition of a new runner, should users be allowed to turn certain ones off at their leisure? 

##### Show of my thoughts:

For **2**, I would imagine just letting it run under a test env and outputting to the same term window as the test runner one after the other would be fine. For example, credo first then the tests... or vice versa... or user choice.

For **4**, I can see it being the case that some people wouldn't want to run both a linter and tests all at once (especially for larger code bases). Letting users turn either one off with an env var or config would be convenient.

Considering both **2** and **4** together, perhaps one term window for each runner with a special flag for running credo. This way, credo and the tests can run concurrently and have visually isolated outputs so that a developer can focus on one at a time.

I'm mostly just trying to figure out what direction this should go in.

**Comment by wpcarro** [comment]
Hi, @lrosa007. You're raising some useful questions.

**1**. Up until now most of the work has been committed directly to `master`. Moving forward I envision feature branches that are PR'd into `master`. We may want to consider introducing a `develop` branch, but I'm more or less ambivalent about this at the current juncture.

**2**. I agree with your suggestions. I hesitate at having `credo` exclusively run in the `test` environment. I think it would make sense to have it activated in `dev` as well.

**3**. I envision the adapter scanning the project for `credo` as a dependency. If a project does not use `credo`, this stage in the pipeline is ignored. If a project does use `credo`, than the `.credo.exs` file should be used. Another consideration is `--strict` mode. I see this parameter being configurable.

**4**. I am envisioning a two-layered approach. Firstly, users configure the pipeline in their project's `config.exs` file. Secondly, users configure settings within an existing `iex` shell. I'm working on a prototype for the `iex` interface that I do not believe will be ready for a few weeks, so for now it makes sense to manage configuration through `config.exs`.

Hopefully these answers point you in the right direction!

**Comment by rvcas** [comment]
@wpcarro yes they do. Thanks!
