### ISSUE TITLE
Feedback when recompilation fails

### ISSUE THREAD

**Issue by cschneid** [urbint/cortex#3]
I had some code that missed an `end`, and when writing the file, nothing happened in my cortex-enabled terminal. After fixing syntax, it started rerunning my tests automatically again.

Some feedback that the code didn't compile would be nice.

**Comment by uesteibar** [comment]
@cschneid I just tried to reproduce this locally and I do get the feedback when removing an `end`.

<img width="796" alt="screen shot 2017-06-28 at 21 08 35" src="https://user-images.githubusercontent.com/7823996/27655552-11b2aa7e-5c46-11e7-8572-bb160219f54e.png">

Could you add a code snippet for which this happened?

**Comment by cschneid** [comment]
Environment: OSX, elixir 1.4, otp 19, tmux, vim

Tmux left pane - vim with a [test file](https://github.com/scoutapp/scout_apm_elixir/blob/master/test/scout_apm/tracing_test.exs) open.

Tmux right pane - `MIX_ENV=test iex -S mix`

Mix.lock (not committed to the repo) - 
```
  "cortex": {:hex, :cortex, "0.1.0", "8d7a58e07659892b8da90d5eb2ea42cfd6fb0461c25b0bef4a4087b93b576a0d", [:mix], [{:exfswatch, "~> 0.4", [hex: :exfswatch, optional: false]}]},
```

When I change line 11 to remove the open square brace, it does not then run the test, and there's no feedback in the terminal.  Then when I fix it, and write, it runs and I see output.

**Comment by cschneid** [comment]
In writing out the issue, I figured out what was up though.

I have my config/test.exs file with `config :logger, backends: []`, to have my unit tests be quiet while running, and focus on the real output.

The error that cortex raises is visible after removing that line (going back to default console output).

Presumably a similar issue would happen if logging was to a file (and not console).

**Comment by uesteibar** [comment]
@cschneid good catch!

After having a quick look it seems there's no way to overwrite the `:logger` configuration for a specific library (which is what we would need to keep being able to keep using `config :logger, backends: []`.

**Comment by cschneid** [comment]
Yeah. I ran into the same thing in the project I linked. Logger is a global, so you can't override it individually per OTP application. Other backends (file one for sure) allow you do that, but not the built-in console one.

At least now it's documented in this issue. Feel free to close if you don't want to make any changes to this project.
