### ISSUE TITLE
Option to clear the IEx screen before each test run

### ISSUE THREAD

**Issue by solomonhawk** [urbint/cortex#32]
Hi, thanks for this awesome library!

I poked around and didn't find anything related to this so I thought I'd pose the question - is there currently a way to get IEx to clear the shell screen before a new test run?

If not, would you be willing to review a patch that adds a call to `IEx.Helpers.clear()` before initiating a test run on code reload? It might be nice to put this behind a config option as well.

Thanks!

**Comment by glittershark** [comment]
Yeah, we'd accept a patch for that.

**Comment by solomonhawk** [comment]
👏
