### ISSUE TITLE
Disable by default?

### ISSUE THREAD

**Issue by wulymammoth** [urbint/cortex#4]
Just a feature request:

When this is added as a dependency, it seems that it's enabled by default. Not all developers in a given project like that, but don't mind having it as a developer dependency, so long as it isn't enabled by default.

**Comment by russmatney** [comment]
I suspect disabling by default would be annoying the majority of our users (definitely would on our team). Can you expand on the reasons it is not desired? Is it interfering with interactivity in iex? Is there anything specific to your application that isn't being handled properly? I'd much rather support whatever those bugs are.

If you'd prefer it to run in the :test env but not in :dev, you can do so with something like:

```elixir
def deps do
  [
    {:cortex, "~> 0.1", only: [:test]}, # note :dev was removed
  ]
end
```

I have not tried it, but you may be able to get away with something like:

```elixir
def deps do
  [
    {:cortex, "~> 0.1", only: []}, # runs in no environment
  ]
end
```

Then you could enable it yourself by adding an env. If that works, you could even wrap the environment in a function that checks for an environmental variable. 

```elixir
def deps do
  [
    {:cortex, "~> 0.1", only: envs_for_cortex()}, # runs in no environment
  ]
end

defp envs_for_cortex do
  case check_for_cortex_enabled_env_var() do
    true -> [:dev, :test]
    nil -> []
  end
end
```

Seems a shame to disable by default though.

**Comment by wulymammoth** [comment]
@russmatney valid questions.

We already use [mix-test.watch](https://github.com/lpil/mix-test.watch) and some people don't think auto-module reloading is a good idea (I was trying to make a case for it, but couldn't convince all parties to agree). I believe some people just want the same workflow across projects as this isn't a feature of IEx by default. 

With `mix-test.watch` it's not intrusive at all, so we have it, even though not all of our developers use it.

Your last example is similar to what I added to the Mixfile, but someone pointed out that it's "just weird having a different `mix.lock` based on an environment variable now".

So my initial thought really was: disable by default, enable by env var...

Alternatively, can I fork? I don't see licensing info, though.

**Comment by rschmukler** [comment]
@sudostack per-your feedback I've added support for enabling cortex via `config.exs`. Furthermore I've added basic environment variable parsing so that you can configure a default and then specify the environment variable used to re-enable cortex. Hopefully this fits your needs.

We still keep it enabled if no configuration is specified, as per @russmatney, we think this is what the vast majority of people using this library will expect and prefer.

PS. Code is released under the MIT license. Feel free to fork, but we'd rather have your contributions helping make the project better than forking so early in the life-cycle.

**Comment by russmatney** [comment]
@sudostack thanks for taking the time and for integrating cortex! I'm still interested in what the quirks of reloaded modules might be – one thought I had was that it could get out of sync with any processes you may have running, though i'm not sure what kind of impact that would have. If there's any fancy interactivity going on, i'd love to know!

Also, per the mix.lock, I did some testing to be sure - the environmental variables passed to `:only` have no impact on the `mix.lock`, only on whether or not the dependencies are included during the startup process. My suggestion would be better suited to the `:runtime` option. [docs here](https://hexdocs.pm/mix/Mix.Tasks.Deps.html)

**Comment by wulymammoth** [comment]
@rschmukler @russmatney Wow! Awesome! Thanks a bunch!

**Comment by wulymammoth** [comment]
@russmatney Yeah, I wasn't running into any quirks. Another developer just thought that we should avoid the REPL for the most part, but I was in complete disagreement. 

You do bring up a good point about the synchronicity, but it's not one I've encountered yet. 

Sorry, I just re-read your example and I just tried it for myself and you're right!
