### ISSUE TITLE
Reload app code when running Phoenix project

### ISSUE THREAD

**Issue by brandonparsons** [urbint/cortex#6]
Hello,

I have my business logic in one umbrella app, served by a phoenix app.

I'd like changes in the business logic umbrella app to cause a recompile and have the changes served by the Phoenix app, but I can't seem to get this working with `cortex`.

I have put the `cortex` dependency in both umbrella app `mix.exs` files, but I'm not seeing anything reload when I make changes.

Any help you could provide would be appreciated.

**Comment by russmatney** [comment]
Per the [readme](https://github.com/urbint/cortex#umbrella-applications), adding `cortex` to an umbrella app's `mix.exs` will not have any effect – you should add it to the `mix.exs` of any child apps within your umbrella app (or apps) that you'd like to be monitored.

If the docs are not clear or this does not resolve your issue, please let us know!

**Comment by brandonparsons** [comment]
Hi @russmatney - I've added Cortex to all of the `mix.exs` files (the umbrella app, and the children app). Nothing is reloading!

**Comment by russmatney** [comment]
Could you provide some more detail about your setup? I'd love to reproduce this. Maybe a sample repo, or steps to recreate this from scratch?

We use cortex all day in both an umbrella and non-umbrella context, and though we don't use Phoenix, that should work the same as any elixir app.

**Comment by brandonparsons** [comment]
I'll ping you via email

**Comment by brandonparsons** [comment]
As discussed, this was either an issue of misconfiguration on my part (fixed by `mix clean`), or the fact I may have forgotten to use `iex -S mix phx.server` rather than `mix phx.server`.

**Comment by russmatney** [comment]
@brandonparsons thanks for pursuing this – I've added a [note to the readme](https://github.com/urbint/cortex#phoenix). Let us know if you run into any issues!
